### ISSUE TITLE
App review tab does not show resume

### ISSUE THREAD

**Issue by oliviabrown9** [TreeHacks/root#130]

**Comment by epicfaace** [comment]
App review tab is currently disabled.

**Comment by theopolisme** [comment]
Was this bug fixed?

**Comment by oliviabrown9** [comment]
@theopolisme I'm not sure if this is an issue because app review is disabled or was closed because not in scope -> @epicfaace Will this work as expected once review is enabled? Otherwise, this will presumably need to be fixed by the time OOS apps are due (two weeks). Passing to Theo to reopen if necessary.

**Comment by theopolisme** [comment]
Will triage at tech meeting tomorrow, thanks.

**Comment by epicfaace** [comment]
Should be working for admins.
