### ISSUE TITLE
Add csv export of applications

### ISSUE THREAD

**Issue by theopolisme** [TreeHacks/root#151]
in addition to json export

**Comment by theopolisme** [comment]
@MYKatz would you be able to take this issue? You should be able to use a library like https://github.com/zemirco/json2csv :)

**Comment by jsutaria** [comment]
@MYKatz something like this too
[help.txt](https://github.com/TreeHacks/root/files/3833364/help.txt)

**Comment by MYKatz** [comment]
> @MYKatz would you be able to take this issue? You should be able to use a library like https://github.com/zemirco/json2csv :)

Yep!
