### ISSUE TITLE
Simplify login screen

### ISSUE THREAD

**Issue by epicfaace** [TreeHacks/root#89]
When people use our application portal, they may already have accounts (if they've applied last year). However, they may not remember this, and thus might have to go through the sign up -> see an error -> sign in process, which is not optimal.

## Proposed solution
- First screen only has a text box for "email". Also show the "sign in with stanford" button at all times.
- Once the user enters in their email, make a network request to see if the account exists. If it exists, show the "Password" textbox and "sign in" buttons. Otherwise, show the textboxes on the signup screen / "signup" button.

**Comment by theopolisme** [comment]
<img width="1665" alt="Screen Shot 2019-10-20 at 10 54 38 AM" src="https://user-images.githubusercontent.com/1410202/67163797-151d6480-f328-11e9-9dc5-e1b07beb8175.png">
